const en = {
    global: {
        english: 'English',
        khmer: 'Khmer',
        light_theme: 'Light Theme',
        dark_theme: 'Dark Theme',
        profile: 'Profile',
        home: 'Home',
        login: 'Login',
        register: 'Register',
        logout: 'Logout',
        search: 'Search',
        add: 'Add',
        create: 'Create',
        update: 'Update',
        delete: 'Delete',
        save: 'Save',
        close: 'Close',
        email: 'Email',
        password: 'Password',
        or: 'Or',
        action: 'Actions',
        used: 'Used',
        remark: 'Remark',
        choose_image: 'Choose Image',
        name_en: 'Name English',
        name_km: 'Name Khmer',
        order: 'Order',
        no_image: 'No Image',
        are_you_sure_you_want_to_delete: 'Are you sure you want to delete',
        no_cancel: 'No, Cancel',
        yes_i_am_sure: "Yes, I'm Sure"
    },

    profile: {
        photo: 'Photo',
        select_new_photo: 'Select A New Photo',
        remove_photo: 'Remove Photo',
        profile_information: 'Profile Information',
        update_your_account_profile_information_and_email_address: "Update your account's profile information and email address.",
        current_password: 'Current Password',
        new_password: 'New Password',
        update_password: 'Update Password',
        ensure_your_account_is_using_a_long: 'Ensure your account is using a long, random password to stay secure.',
        two_factor_authentication: 'Two Factor Authentication',
        add_additional_security_to_your_account_using_two_factor_authentication: 'Add additional security to your account using two factor authentication.',
        you_have_not_enabled_two_factor_authentication: 'You have not enabled two factor authentication.',
        when_two_factor_authentication_is_enabled: "When two factor authentication is enabled, you will be prompted for a secure, random token during authentication. You may retrieve this token from your phone's Google Authenticator application.",
        enable: 'Enable',
        browser_sessions: 'Browser Sessions',
        manage_and_log_out_your_active_sessions_on_other_browsers_and_devices: 'Manage and log out your active sessions on other browsers and devices.',
        if_necessary: 'If necessary, you may log out of all of your other browser sessions across all of your devices. Some of your recent sessions are listed below; however, this list may not be exhaustive. If you feel your account has been compromised, you should also update your password.',
        this_device: 'This device',
        log_out_other_browser_sessions: 'Log Out Other Browser Sessions',
        delete_account: 'Delete Account',
        permanently_delete_your_account: 'Permanently delete your account.',
        once_your_account_is_deleted: 'Once your account is deleted, all of its resources and data will be permanently deleted. Before deleting your account, please download any data or information that you wish to retain.',
        your_email_address_is_unverified: 'Your email address is unverified.',
        click_here_to_resend_the_verification_email: 'Click here to re-send the verification email.',
        a_new_verification_link_has_been_sent_to_your_email_address: 'A new verification link has been sent to your email address.',
        you_have_enabled_two_factor_authentication: 'You have enabled two factor authentication.',
        finish_enabling_two_factor_authentication: 'Finish enabling two factor authentication.',
        to_finish_enabling_two_factor_authentication: "To finish enabling two factor authentication, scan the following QR code using your phone's authenticator application or enter the setup key and provide the generated OTP code.",
        two_factor_authentication_is_now_enabled: "Two factor authentication is now enabled. Scan the following QR code using your phone's authenticator application or enter the setup key.",
        setup_key: 'Setup Key',
        store_these_recovery_codes_in_a_secure_password_manager: 'Store these recovery codes in a secure password manager. They can be used to recover access to your account if your two factor authentication device is lost.',
        confirm: 'Confirm',
        regenerate_recovery_codes: 'Regenerate Recovery Codes',
        show_recovery_codes: 'Show Recovery Codes',
        disable: 'Disable',
        last_active: 'Last active',
        done: 'Done',
        please_enter_your_password_to_confirm: 'Please enter your password to confirm you would like to log out of your other browser sessions across all of your devices.',
        are_you_sure_you_want_to_delete_your_account: "Are you sure you want to delete your account? Once your account is deleted, all of its resources and data will be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.",
        for_your_security: 'For your security, please confirm your password to continue.',
    },

    login: {
        remember: 'Remember',
        forgot_password: 'Forgot Password',
        do_not_have_an_account: "Don't have an account",
        create_an_account: 'Create an account',
    },

    register: {
        name: 'Name',
        confirm_password: 'Confirm Password',
        sign_up: 'Sign Up',
        already_have_an_account: 'Already have an account',
    },

    menu: {
        dashboard: 'Dashboard',
        menu_system: 'Menu System',
        parameter: 'Parameter',
        company_profile: 'Company Profile',
        news_type: 'News Type',
        news_information: 'News Information',
        about_news_type: 'About News Type',
        sponsor: 'Sponsor',
        about_news_description: 'About News Description',
    },

    menu_system: {
        name: 'Name',
        url: 'Url',
        icon: 'Icon',
    },

    parameter: {
        parameter_code: 'Parameter Code',
        value: 'Value',
        text_km: 'Text KM',
        text_en: 'Text EN',
    },

    company_profile: {
        created_date: 'Created Date',
        phone: 'Phone',
        location: 'Location',
        logo: 'Logo'
    },

    news_information: {
        title_en: 'Title English',
        title_km: 'Title Khmer',
        url_video: 'Url Video',
        latitude: 'Latitude',
        longitude: 'Longitude',
        use_my_current_location: 'Use My Current Location',
        reset: 'Reset',
        crop: 'Crop',
        browse: 'Browse',
    },

    sponsor: {
        sponsor_name: 'Sponsor Name',
        contact: 'Contact'
    },
};

export default { en };
